### ISSUE TITLE
Yep build error 

### ISSUE THREAD

**Issue by dmgnr** [xzxADIxzx/Copy-Link-and-Join#2]
https://github.com/5UP3R-D1N/Copy-Link-and-Join/actions/runs/4895995076/jobs/8742250102
Can you specify the exact gradle version this thing need to be built on?

**Comment by xzxADIxzx** [comment]
https://github.com/xzxADIxzx/Copy-Link-and-Join/blob/main/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by xzxADIxzx** [comment]
But if you want to know, the problem may be in version of Java; My Java version is 17
