### ISSUE TITLE
Can player without CLaJ like join with normal add server?

### ISSUE THREAD

**Issue by kennarddh** [xzxADIxzx/Copy-Link-and-Join#3]
And this ClaJ button just appear when I use Foo client

**Comment by xzxADIxzx** [comment]
No, players without CLAJ cannot join to CLAJ server, because it's working like VPN.

**Comment by kennarddh** [comment]
Can mobile player use it? Because I use foo client and that button just appear and i think foo client is not supported for mobile mindustry.

**Comment by xzxADIxzx** [comment]
Yeah, Scheme Size (lite) works on both desktop and mobile.

**Comment by kennarddh** [comment]
Ok
